/***************************************************************************
 *   Copyright (C) 2006 by Matteo Franchin (fnch@libero.it)                *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program; if not, write to the                         *
 *   Free Software Foundation, Inc.,                                       *
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 ***************************************************************************/

#include <assert.h>
#include <stdlib.h>

#include "types.h"
#include "messages.h"
#include "typesys.h"
#include "virtmach.h"
#include "cmpproc.h"
#include "compiler.h"
#include "value.h"
#include "autogen.h"
#include "vmsymstuff.h"

/* Autogeneration for structures */
static int My_Autogen_Struc_Proc(BoxCmp *c, BoxType t_child, BoxType t_parent) {
  size_t initial_proc_size;
  ValueStrucIter vsi;
  Value v_struc;

  Value_Init(& v_struc, c->cur_proc);
  Value_Setup_As_Parent(& v_struc, t_parent);
  initial_proc_size = CmpProc_Get_Code_Size(c->cur_proc);
  for(ValueStrucIter_Init(& vsi, & v_struc, c->cur_proc);
      vsi.has_next; ValueStrucIter_Do_Next(& vsi)) {
    Value v_child;
    Value_Init(& v_child, c->cur_proc);
    Value_Setup_As_Type(& v_child, t_child);
    (void) Value_Emit_Call_Or_Blacklist(& vsi.v_member, & v_child);
  }
  ValueStrucIter_Finish(& vsi);

  return (CmpProc_Get_Code_Size(c->cur_proc) > initial_proc_size);
}

/* Here we assume that the procedure child@parent is not registered! */
BoxType Autogen_Procedure(BoxCmp *c, BoxType t_child, BoxType t_parent) {
  TS *ts = & c->ts;
  BoxType t_proc = BOXTYPE_NONE;
  int autogenerated = 0;

  if (!TS_Is_Special(t_child)) 
    return t_proc;

  else {
    Type ct_parent = TS_Get_Core_Type(ts, t_parent);
    CmpProc *save_cur_proc = c->cur_proc;
    c->cur_proc = CmpProc_New(c, CMPPROCSTYLE_SUB);

    switch(TS_Get_Kind(ts, ct_parent)) {
    case TS_KIND_STRUCTURE:
      autogenerated = My_Autogen_Struc_Proc(c, t_child, t_parent);
      break;

    case TS_KIND_SUBTYPE:
      break;
    default:
      break;
    }
 
    /* If the procedure is not empty, we register it */
    if (autogenerated) {
      /* Create the procedure type and obtain its name */
      t_proc = TS_Procedure_New(ts, t_parent, t_child, 3);
      char *proc_name = TS_Name_Get(& c->ts, t_proc);
      CmpProc_Set_Name(c->cur_proc, proc_name);
      BoxMem_Free(proc_name);

      /* Define the symbol associated to the procedure */
      BoxVMSymID sym_id = CmpProc_Get_Sym(c->cur_proc);
      BoxVMCallNum call_num = CmpProc_Get_Call_Num(c->cur_proc);
      ASSERT_TASK( BoxVMSym_Def_Call(c->vm, sym_id, call_num) );

      /* Register the procedure in the type system */
      TS_Procedure_Register(ts, t_proc, sym_id);


    } else {
      /* Here we should destroy the code, since the procedure is not
       * going to be installed)
       */
    }

    CmpProc_Destroy(c->cur_proc);
    c->cur_proc = save_cur_proc;
    return t_proc;
  }
}


#if 0
/*#include "messages.h"*/
#include "str.h"
#include "typesys.h"

static void Create_Structure_Method(Type parent, Type child, int kind) {
  Type parent_ct = TS_Core_Type(cmp->ts, parent);
  Type found;

  TS_Procedure_Search(cmp->ts, & found, (Type *) NULL,
                      parent_ct, child, kind);
  if (found == TS_TYPE_NONE) {
    Expr structure_e, member_e, iter_e;
    int members_left;

    ASSERT_TASK( Box_Def_Begin(parent_ct, child, kind) );
    ASSERT_TASK( Box_Parent_Get(& structure_e, 0) );

    iter_e = structure_e;
    Expr_Struc_Iter(& member_e, & iter_e, & members_left);
    while (members_left > 0) {
      Type member_t = member_e.type;
      if (!TS_Is_Fast(cmp->ts, member_t)) {
        if (member_e.is.value && Tym_Type_Size(member_e.resolved) > 0) {
          (void) Box_Procedure_Call_Void(& member_e, child, kind,
                                         BOX_MSG_SILENT);
        }
      }

      Expr_Struc_Iter(& member_e, & iter_e, & members_left);
    };

    ASSERT_TASK( Box_Def_End() );
  }

}

void Auto_Acknowledge_Call(Type parent, Type child, int kind) {
  /* We check if the child is a special type: ([), (]), (;), (\).
   * These are the case for which we need to propagate the methods from
   * contained objects to their container.
   */
  if (TS_Is_Special(child)) {
    Type found;
    TS_Procedure_Search(cmp->ts, & found, (Type *) NULL,
                        parent, child, kind);
    if (found != TS_TYPE_NONE) {
      if (child == TYPE_DESTROY) {
        UInt sym_num;
        Int call_num = BoxVM_Alloc_Method_Get(cmp->vm, parent, child);
        if (call_num >= 0) return;
        TS_Procedure_Sym_Num_Get(cmp->ts, & sym_num, found);
        ASSERT_TASK( VM_Sym_Alloc_Method_Register(cmp->vm, sym_num,
                                                  parent, child) );
      }
      return;

    } else {
    }
  }
}
#endif

