.PHONY: all dev2

all:
	libtoolize --ltdl
	aclocal -I ./m4
	autoconf
	autoheader
	automake --add-missing

# Here we show how one can use another version of the libtool
# installed on the user's directory
dev2:
	~/local/bin/libtoolize --ltdl
	aclocal -I ~/local/share/aclocal # --verbose
	autoconf
	autoheader
	automake-1.10 --add-missing

dev3:
	~/local/bin/libtoolize --ltdl
	~/local/bin/aclocal -I ~/local/share/aclocal -I ./m4 # --verbose
	~/local/bin/autoconf
	~/local/bin/autoheader
	~/local/bin/automake --add-missing

