BOX=~/local/bin/box

all: poly.png line.png circle.png

poly.png: poly.box icon_theme.box
	$(BOX) -l g $<

line.png: line.box icon_theme.box
	$(BOX) -l g $<

circle.png: circle.box icon_theme.box
	$(BOX) -l g $<

